name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    # Only following types are handled by the action, but one can default to all as well
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Release Drafter
        uses: release-drafter/release-drafter@v6
        id: release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bumping package versions
        if: ${{ steps.release-drafter.outputs.tag_name != '' && !startsWith(steps.release-drafter.outputs.tag_name, 'untagged')}}
        run: |
          npm version ${{ steps.release-drafter.outputs.tag_name }} --no-git-tag-version
        working-directory: ${{ env.working-diretory }}
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        if: ${{ steps.release-drafter.outputs.tag_name != '' && !startsWith(steps.release-drafter.outputs.tag_name, 'untagged')}}
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Changes to publish ${{ steps.release-drafter.outputs.tag_name }}"
          base: main
          title: ${{ steps.release-drafter.outputs.tag_name }}
          body: ${{ steps.release-drafter.outputs.body }}
          branch: ${{ steps.release-drafter.outputs.tag_name }}
          labels: |
            ${{ steps.release-drafter.outputs.tag_name }}
            release
